-- ╔════════════════════════════════════════════════════════════════════╗
-- ║     COMPREHENSIVE INDIAN CAR MODELS DATABASE (2026)                 ║
-- ║     Total Models: 227                                         ║
-- ╚════════════════════════════════════════════════════════════════════╝

-- Schema Definition (PostgreSQL Compatible)
CREATE TABLE IF NOT EXISTS car_models (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_car UNIQUE (make, model)
);

CREATE INDEX idx_car_models_make ON car_models(make);
CREATE INDEX idx_car_models_model ON car_models(model);

-- Trigger for updating timestamp
CREATE TRIGGER update_car_models_timestamp
  BEFORE UPDATE ON car_models
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Data Insertion
INSERT INTO car_models (make, model, type) VALUES
('Maruti Suzuki', 'Swift', 'Hatchback'),
('Maruti Suzuki', 'Baleno', 'Hatchback'),
('Maruti Suzuki', 'Dzire', 'Sedan'),
('Maruti Suzuki', 'Ertiga', 'MPV'),
('Maruti Suzuki', 'Brezza', 'SUV'),
('Maruti Suzuki', 'Alto', 'Hatchback'),
('Maruti Suzuki', 'Wagon R', 'Hatchback'),
('Maruti Suzuki', 'Celerio', 'Hatchback'),
('Maruti Suzuki', 'FRONX', 'SUV'),
('Maruti Suzuki', 'Vitara Brezza', 'SUV'),
('Maruti Suzuki', 'XL6', 'MPV'),
('Maruti Suzuki', 'Ciaz', 'Sedan'),
('Maruti Suzuki', 'Grand Vitara', 'SUV'),
('Maruti Suzuki', 'Jimny', 'SUV'),
('Maruti Suzuki', 'S-Presso', 'Hatchback'),
('Maruti Suzuki', 'Ritz', 'Hatchback'),
('Maruti Suzuki', 'Ignis', 'Hatchback'),
('Maruti Suzuki', 'Alto K10', 'Hatchback'),
('Maruti Suzuki', 'Tour H1', 'Hatchback'),
('Maruti Suzuki', 'Victoris', 'Sedan'),
('Maruti Suzuki', '800', 'Hatchback'),
('Maruti Suzuki', 'Maruti 1000', 'Sedan'),
('Maruti Suzuki', 'Esteem', 'Sedan'),
('Hyundai', 'i20', 'Hatchback'),
('Hyundai', 'Creta', 'SUV'),
('Hyundai', 'Verna', 'Sedan'),
('Hyundai', 'Venue', 'SUV'),
('Hyundai', 'Eon', 'Hatchback'),
('Hyundai', 'i10', 'Hatchback'),
('Hyundai', 'Grand i10', 'Hatchback'),
('Hyundai', 'Grand i10 Nios', 'Hatchback'),
('Hyundai', 'Aura', 'Sedan'),
('Hyundai', 'Tucson', 'SUV'),
('Hyundai', 'Creta Electric', 'SUV'),
('Hyundai', 'Exter', 'SUV'),
('Hyundai', 'Kona', 'SUV'),
('Hyundai', 'Nexo', 'SUV'),
('Hyundai', 'Santro', 'Hatchback'),
('Hyundai', 'Santro Xing', 'Hatchback'),
('Hyundai', 'i20 N Line', 'Hatchback'),
('Hyundai', 'Getz', 'Hatchback'),
('Hyundai', 'i30', 'Hatchback'),
('Tata', 'Nexon', 'SUV'),
('Tata', 'Harrier', 'SUV'),
('Tata', 'Safari', 'SUV'),
('Tata', 'Tiago', 'Hatchback'),
('Tata', 'Tigor', 'Sedan'),
('Tata', 'Altroz', 'Hatchback'),
('Tata', 'Punch', 'SUV'),
('Tata', 'Curvv', 'SUV'),
('Tata', 'Sierra', 'SUV'),
('Tata', 'Avinya', 'SUV'),
('Tata', 'Nexon EV', 'SUV'),
('Tata', 'Harrier EV', 'SUV'),
('Tata', 'Punch EV', 'SUV'),
('Tata', 'Sierra EV', 'SUV'),
('Tata', 'Altroz Racer', 'Hatchback'),
('Tata', 'Xpres', 'Sedan'),
('Tata', 'Xpres T EV', 'Sedan'),
('Tata', 'Tiago NRG', 'Hatchback'),
('Tata', 'Indigo', 'Sedan'),
('Tata', 'Indica', 'Hatchback'),
('Mahindra', 'Scorpio', 'SUV'),
('Mahindra', 'Scorpio N', 'SUV'),
('Mahindra', 'XUV700', 'SUV'),
('Mahindra', 'XUV500', 'SUV'),
('Mahindra', 'Thar', 'SUV'),
('Mahindra', 'Thar ROXX', 'SUV'),
('Mahindra', 'Bolero', 'SUV'),
('Mahindra', 'Bolero Neo', 'SUV'),
('Mahindra', 'Bolero Neo Plus', 'SUV'),
('Mahindra', 'XUV300', 'SUV'),
('Mahindra', 'XUV3XO', 'SUV'),
('Mahindra', 'XUV3XO EV', 'SUV'),
('Mahindra', 'BE 6', 'SUV'),
('Mahindra', 'XEV 9e', 'SUV'),
('Mahindra', 'XEV 9S', 'SUV'),
('Mahindra', 'Alturas G4', 'SUV'),
('Mahindra', 'Bolero Camper', 'SUV'),
('Mahindra', 'XUV 7XO', 'SUV'),
('Mahindra', 'Xylo', 'MPV'),
('Mahindra', 'Quanto', 'SUV'),
('Honda', 'City', 'Sedan'),
('Honda', 'Amaze', 'Sedan'),
('Honda', 'Jazz', 'Hatchback'),
('Honda', 'HR-V', 'SUV'),
('Honda', 'Elevate', 'SUV'),
('Honda', 'CR-V', 'SUV'),
('Honda', 'Accord', 'Sedan'),
('Honda', 'Civic', 'Sedan'),
('Toyota', 'Innova Crysta', 'MPV'),
('Toyota', 'Innova Hycross', 'MPV'),
('Toyota', 'Fortuner', 'SUV'),
('Toyota', 'Glanza', 'Hatchback'),
('Toyota', 'Vellfire', 'MPV'),
('Toyota', 'Camry', 'Sedan'),
('Toyota', 'Land Cruiser 300', 'SUV'),
('Toyota', 'Land Cruiser Prado', 'SUV'),
('Toyota', 'Hilux', 'Pickup'),
('Toyota', 'Corolla', 'Sedan'),
('Kia', 'Seltos', 'SUV'),
('Kia', 'Sonet', 'SUV'),
('Kia', 'Carens', 'MPV'),
('Kia', 'Carens EV', 'MPV'),
('Kia', 'Syros', 'SUV'),
('Kia', 'EV6', 'SUV'),
('Kia', 'EV9', 'SUV'),
('Skoda', 'Rapid', 'Sedan'),
('Skoda', 'Slavia', 'Sedan'),
('Skoda', 'Octavia', 'Sedan'),
('Skoda', 'Superb', 'Sedan'),
('Skoda', 'Kodiaq', 'SUV'),
('Skoda', 'Kylaq', 'SUV'),
('Skoda', 'Kushaq', 'SUV'),
('Skoda', 'Karoq', 'SUV'),
('Volkswagen', 'Polo', 'Hatchback'),
('Volkswagen', 'Vento', 'Sedan'),
('Volkswagen', 'Virtus', 'Sedan'),
('Volkswagen', 'Taigun', 'SUV'),
('Volkswagen', 'Tiguan', 'SUV'),
('Volkswagen', 'T-Roc', 'SUV'),
('Volkswagen', 'Tayron', 'SUV'),
('Citroen', 'C3', 'Hatchback'),
('Citroen', 'C3 Aircross', 'SUV'),
('Citroen', 'Basalt', 'SUV'),
('Citroen', 'C5 Aircross', 'SUV'),
('Jeep', 'Compass', 'SUV'),
('Jeep', 'Wrangler', 'SUV'),
('Jeep', 'Meridian', 'SUV'),
('Jeep', 'Grand Cherokee', 'SUV'),
('Renault', 'Kiger', 'SUV'),
('Renault', 'Duster', 'SUV'),
('Renault', 'Kwid', 'Hatchback'),
('Renault', 'Triber', 'MPV'),
('MG', 'Hector', 'SUV'),
('MG', 'Astor', 'SUV'),
('MG', 'Comet', 'Hatchback'),
('MG', 'Comet EV', 'Hatchback'),
('MG', 'Windsor EV', 'SUV'),
('MG', 'ZS EV', 'SUV'),
('MG', 'Cyberster', 'Coupe'),
('Nissan', 'Magnite', 'SUV'),
('Nissan', 'Kicks', 'SUV'),
('Nissan', 'Terrano', 'SUV'),
('Nissan', 'Ariya', 'SUV'),
('Datsun', 'Redi-GO', 'Hatchback'),
('Datsun', 'GO', 'Hatchback'),
('Datsun', 'GO+', 'MPV'),
('Audi', 'A4', 'Sedan'),
('Audi', 'A6', 'Sedan'),
('Audi', 'Q3', 'SUV'),
('Audi', 'Q5', 'SUV'),
('Audi', 'Q7', 'SUV'),
('Audi', 'Q8', 'SUV'),
('BMW', 'X1', 'SUV'),
('BMW', 'X3', 'SUV'),
('BMW', 'X5', 'SUV'),
('BMW', 'X7', 'SUV'),
('BMW', '3 Series', 'Sedan'),
('BMW', '5 Series', 'Sedan'),
('BMW', 'M5', 'Sedan'),
('BMW', 'iX1 LWB', 'SUV'),
('Mercedes-Benz', 'C-Class', 'Sedan'),
('Mercedes-Benz', 'E-Class', 'Sedan'),
('Mercedes-Benz', 'S-Class', 'Sedan'),
('Mercedes-Benz', 'GLA', 'SUV'),
('Mercedes-Benz', 'GLB', 'SUV'),
('Mercedes-Benz', 'GLC', 'SUV'),
('Mercedes-Benz', 'GLE', 'SUV'),
('Mercedes-Benz', 'G-Class', 'SUV'),
('Land Rover', 'Discovery', 'SUV'),
('Land Rover', 'Discovery Sport', 'SUV'),
('Land Rover', 'Range Rover', 'SUV'),
('Land Rover', 'Range Rover Evoque', 'SUV'),
('Land Rover', 'Range Rover Velar', 'SUV'),
('Land Rover', 'Defender', 'SUV'),
('Porsche', '911', 'Coupe'),
('Porsche', 'Cayenne', 'SUV'),
('Porsche', 'Macan', 'SUV'),
('Porsche', 'Panamera', 'Sedan'),
('Jaguar', 'XE', 'Sedan'),
('Jaguar', 'XF', 'Sedan'),
('Jaguar', 'F-Pace', 'SUV'),
('Lexus', 'LX', 'SUV'),
('Lexus', 'RX', 'SUV'),
('Lexus', 'ES', 'Sedan'),
('Rolls-Royce', 'Spectre', 'Coupe'),
('Rolls-Royce', 'Ghost', 'Sedan'),
('Rolls-Royce', 'Phantom', 'Sedan'),
('Bentley', 'Flying Spur', 'Sedan'),
('Bentley', 'Continental', 'Coupe'),
('Bentley', 'Bentayga', 'SUV'),
('Lamborghini', 'Revuelto', 'Coupe'),
('Lamborghini', 'Huracan', 'Coupe'),
('Ferrari', '812', 'Coupe'),
('Ferrari', 'F8', 'Coupe'),
('McLaren', 'GT', 'Coupe'),
('McLaren', '570S', 'Coupe'),
('Volvo', 'S90', 'Sedan'),
('Volvo', 'XC40', 'SUV'),
('Volvo', 'XC60', 'SUV'),
('Volvo', 'XC90', 'SUV'),
('Volvo', 'EX30', 'SUV'),
('Volvo', 'EX40', 'SUV'),
('Mazda', 'CX-5', 'SUV'),
('Mazda', 'CX-3', 'SUV'),
('Subaru', 'Forester', 'SUV'),
('Subaru', 'XV', 'SUV'),
('Fiat', 'Abarth', 'Hatchback'),
('BYD', 'Atto 2', 'SUV'),
('BYD', 'Song Plus DM-i', 'SUV'),
('VinFast', 'VF8', 'SUV'),
('VinFast', 'VF9', 'SUV'),
('Vayve Mobility', 'Eva', 'Hatchback'),
('Force Motors', 'Gurkha', 'SUV'),
('ISUZU', 'D-Max', 'Pickup'),
('ISUZU', 'MU-X', 'SUV'),
('Chevrolet', 'Beat', 'Hatchback'),
('Chevrolet', 'Sail', 'Sedan'),
('Chevrolet', 'Enjoy', 'MPV'),
('Chevrolet', 'Cruze', 'Sedan'),
('Hindustan', 'Ambassador', 'Sedan'),
('Hindustan', 'Contessa', 'Sedan'),
('Premier', '800', 'Hatchback'),
('Premier', 'Padmini', 'Sedan'),
('Ashok Leyland', 'Stile', 'Sedan'),
('Ashok Leyland', 'Stile Plus', 'Sedan');

-- ═══════════════════════════════════════════════════════════════════
-- DATABASE SUMMARY
-- ═══════════════════════════════════════════════════════════════════
-- Total Models: 227
-- Total Brands: 40
-- Vehicle Types: 6
